### ISSUE TITLE
No ECB in the dropdown.

### ISSUE THREAD

**Issue by rickcj** [mage2pro/currency-convert#1]
I have installed onto Magento 2.2.7 and can see Mage2.pro in the configuration. There is a fixer.io custom api credentials, but no ECB settings and no ECB in the dropdown.

I have re-indexed and cleared the cache.

Kind regards,

Chris

**Comment by dmitrii-fediuk** [comment]
Maybe you have not recompiled the Magento's code.

**Comment by rickcj** [comment]
Hi,

I did, but i'll try re-running.

Why does it include settings for Fixer.io, when this is completely different?

Kind regards,

Chris

**Comment by rickcj** [comment]
I tried it again and logged out and back in and now ECB is showing.

Thanks for this module, Magento really should have this working from a clean install.
