### ISSUE TITLE
Uninstall this and all df_

### ISSUE THREAD

**Issue by rickcj** [mage2pro/currency-convert#2]
I installed this and it seems to have been working fine, but noticed I can't save bundle products:

Could not save child: "Unknown entity type: Magento\Bundle\Model\Selection\Interceptor requested"

Searching doesn't come up with many results, but one of the few was https://github.com/mage2pro/ipay88/issues/17

I tried disabling the dfe_currencyconvert, but wonder if the issue relates to one of the many df_ modules?

**Comment by dmitrii-fediuk** [comment]
You can hire me in Upwork to solve your problems: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by rickcj** [comment]
I just want to know how to fully uninstall this currency converter and your other components?

**Comment by dmitrii-fediuk** [comment]
Do not waste my working time for free. I do not support for free.
