### ISSUE TITLE
«Interface "Zend_Validate_Interface" not found»

### ISSUE THREAD

**Issue by git-seb** [mage2pro/currency-convert#3]
Shows the following error:
There is an error in /vendor/mage2pro/core/Zf/Validate.php at line: 11
Interface "Zend_Validate_Interface" not found#0 /vendor/composer/ClassLoader.php(582): include()

In Magento 2.4.6: Zend_Validate_Interface has been replaced with laminas-validator

**Comment by dmitrii-fediuk** [comment]
Fixed in [`mage2pro/core` 9.5.2](https://github.com/mage2pro/core/releases/tag/9.5.2).
